import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import store from "@/store/store";
import { Provider } from "@reduxjs/toolkit";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/ui/Navbar";

export const metadata: Metadata = {
  title: "Next Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body className={inter.className}>
          <Navbar />
          <main>{children}</main>
          <Toaster />
        </body>
      </Provider>
    </html>
  );
}
